AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  Include:
    - "backend/**/*.rb"
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "test/**/*"
    - "../frontend/**/*"
    - "**/Rakefile"
    - "**/Gemfile"
    - "**/Capfile"
    - "**/CamelCase.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 240

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Max: 2000

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: false
