source 'https://rubygems.org'

ruby '3.4.4'
gem 'rails', '~> 7.1'

# DB
gem 'pg', '>= 1.4'  # PostgreSQLドライバ

# 認証
gem 'devise'                      # ログイン/ユーザー管理
gem 'devise-jwt'                 # JWT連携
gem 'omniauth'                   # OAuth2
gem 'omniauth-google-oauth2'    # Google認証
gem 'omniauth-facebook'         # Facebook認証

# API構築
gem 'jbuilder'                   # JSON出力
gem 'rack-cors'                 # CORS対応
gem 'active_model_serializers'  # JSONの構造制御（任意）

# その他
gem 'dotenv-rails'              # .env読み込み
gem 'puma'                      # WSGI相当のサーバー（デフォルト）
