# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.8'
gem 'rails', '~> 7.2'

# DB
gem 'pg', '>= 1.4' # PostgreSQL

# 認証
gem 'devise' # ログイン/ユーザー管理
gem 'devise-jwt' # JWT連携
gem 'devise_token_auth' # outh認証
gem 'omniauth' # OAuth2
gem 'omniauth-facebook'         # Facebook認証
gem 'omniauth-google-oauth2'    # Google認証

# API構築
gem 'active_model_serializers' # JSONの構造制御
gem 'jbuilder' # JSON出力
gem 'rack-cors' # CORS対応

# その他
gem 'dotenv-rails'              # .env読み込み
gem 'puma'                      # アプリケーションサーバー

gem 'bootsnap', require: false
gem 'sprockets-rails'

gem 'rails-i18n'

group :development, :test do
  gem 'brakeman', require: false
  gem 'bundler-audit', require: false
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'simplecov', require: false
  gem 'simplecov-lcov', require: false
  gem 'solargraph', require: false
end

gem 'letter_opener_web', '~> 3.0', group: :development
